baseURL = 'https://blog.vhmontes.com/'
languageCode = 'en-us'
title = 'Victor Hugo'
theme = 'ananke'

DefaultContentLanguage = "en"

enableRobotsTXT = true

[params]
	social = true

[languages]
  [languages.en]
    title = 'Victor Hugo'
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
